# Generated by Django 5.0.6 on 2024-05-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_c_user_c_encrpted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c_user',
            name='c_encrpted',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
